import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name='theme-color' content='var(--color-primary)' />
      </Head>

      <main className={styles.main}>
        This is the main content
      </main>
    </div>
  )
}
