### Get followers admin2
GET http://localhost:8080/api/user/22e0cfcd-fb1e-4750-b88d-96697fe1e196/followers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDZmZTQ1ZmMtMTExYi00M2Y2LWE1OTgtNzU5NjlmNmY5N2RmIiwidXNlcm5hbWUiOiJjYXJsb3MiLCJmaXJzdF9uYW1lIjoiQ2FybG9zIiwibGFzdF9uYW1lIjoiRGUgTGEgUm9jYSIsInByb2ZpbGVfaW1hZ2VfdXJsIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyMi0wMy0wN1QxMTowMTozMC4wMDBaIiwiaWF0IjoxNjQ2NzY3NjY5fQ.v2hGnk2aUtQiiog6TdoD_rndI8NY0AWCX9M1TW5FGQ0

### Follow admin 2

POST http://localhost:8080/api/user/22e0cfcd-fb1e-4750-b88d-96697fe1e196/followers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDZmZTQ1ZmMtMTExYi00M2Y2LWE1OTgtNzU5NjlmNmY5N2RmIiwidXNlcm5hbWUiOiJjYXJsb3MiLCJmaXJzdF9uYW1lIjoiQ2FybG9zIiwibGFzdF9uYW1lIjoiRGUgTGEgUm9jYSIsInByb2ZpbGVfaW1hZ2VfdXJsIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyMi0wMy0wN1QxMTowMTozMC4wMDBaIiwiaWF0IjoxNjQ2ODAxMDY1fQ.-KHt8tHli31KOf-D4x20QbSRPy-G9y-N-GvhFeJSdOo

### Follow admin2 as admin
POST http://localhost:8080/api/user/22e0cfcd-fb1e-4750-b88d-96697fe1e196/followers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTU1MGU1YjUtMzIxNS00N2ZmLWE1YmUtYzYwMDNlZWIyMjMyIiwidXNlcm5hbWUiOiJhZG1pbiIsImZpcnN0X25hbWUiOiJBZG1pbmlzdHJhdG9yIiwibGFzdF9uYW1lIjoiQk9UIiwicHJvZmlsZV9pbWFnZV91cmwiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIyLTAzLTA4VDAwOjE5OjU2LjAwMFoiLCJpYXQiOjE2NDY4MDE0Njh9.z32zpvV2q6A6l0hdzcbdSLUOMZ3FHzc6aNrjixSRRak

### Unfollow admin2 as admin
DELETE http://localhost:8080/api/user/22e0cfcd-fb1e-4750-b88d-96697fe1e196/followers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTU1MGU1YjUtMzIxNS00N2ZmLWE1YmUtYzYwMDNlZWIyMjMyIiwidXNlcm5hbWUiOiJhZG1pbiIsImZpcnN0X25hbWUiOiJBZG1pbmlzdHJhdG9yIiwibGFzdF9uYW1lIjoiQk9UIiwicHJvZmlsZV9pbWFnZV91cmwiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIyLTAzLTA4VDAwOjE5OjU2LjAwMFoiLCJpYXQiOjE2NDY4MDE0Njh9.z32zpvV2q6A6l0hdzcbdSLUOMZ3FHzc6aNrjixSRRak